# Generated by Django 5.1.5 on 2025-01-31 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_is_staff_alter_user_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onetimepassword',
            name='user',
        ),
        migrations.AddField(
            model_name='onetimepassword',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name=''),
            preserve_default=False,
        ),
    ]
