# Generated by Django 5.1.5 on 2025-01-31 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_onetimepassword_user_onetimepassword_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimepassword',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email Address'),
        ),
    ]
