# Generated by Django 5.1.5 on 2025-01-31 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_onetimepassword_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='onetimepassword',
            name='isVerified',
            field=models.BooleanField(default=False),
        ),
    ]
