# Generated by Django 5.1.5 on 2025-01-31 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_onetimepassword_isverified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimepassword',
            name='email',
            field=models.EmailField(max_length=200, verbose_name='Email Address'),
        ),
    ]
