# Generated by Django 5.1.5 on 2025-02-01 07:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onetimepassword',
            name='email',
        ),
        migrations.RemoveField(
            model_name='onetimepassword',
            name='isVerified',
        ),
        migrations.AddField(
            model_name='onetimepassword',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
