# Generated by Django 5.1.5 on 2025-02-01 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_onetimepassword_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimepassword',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
