# Generated by Django 5.1.5 on 2025-02-02 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_otpmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTPModel',
        ),
    ]
